# 配置应用信息
server:
  port: 8080
# 配置数据库 MySQL Redis
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redis_stock?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&useAffectedRows=true&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    password: